### ISSUE TITLE
Visualation Problem

### ISSUE THREAD

**Issue by diablordking** [Crypto-AI/Stocktalk#3]
`

from stocktalk.visualize import readUpdates, extrapolate, getPlot

from stocktalk import streaming
from stocktalk import visualize

# Credentials to access Twitter API 
API_KEY = '**********************'
API_SECRET = '*************************'
ACCESS_TOKEN = '***************************'
ACCESS_TOKEN_SECRET = '**********************************'
credentials = [API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET]

# First element must be ticker/name, proceeding elements are extra queries
TSLA = ['TSLA', 'Tesla']
SNAP = ['SNAP', 'Snapchat']
AAPL = ['AAPL', 'Apple']
AMZN = ['AMZN', 'Amazon']

# Variables
tickers = [TSLA,SNAP,AAPL,AMZN]  # Used for identification purposes
queries =  TSLA+SNAP+AAPL+AMZN   # Filters tweets containing one or more query 
refresh = 30                     # Process and log data every 30 seconds

# Create a folder to collect logs and temporary files
path = "./data"

streaming(credentials, tickers, queries, refresh, path, \
realtime=True, logTracker=True, logTweets=True, logSentiment=True, debug=True)

tickers = ['TSLA','SNAP','AAPL','AMZN']
refresh = 30

visualize(tickers, refresh, path)`

this my code I run bokeh server. but ı only got empty page. what ı am doing wrong ?

**Comment by anfederico** [comment]
Could you send me the error message? It should be in your terminal, right after you load the page (if it comes up blank).

**Comment by diablordking** [comment]
![screenshot from 2017-03-23 10-53-53](https://cloud.githubusercontent.com/assets/19604984/24237627/c34e6374-0faf-11e7-871e-0d073a081818.png)
![screenshot from 2017-03-23 11-00-15](https://cloud.githubusercontent.com/assets/19604984/24237628/c3538de0-0faf-11e7-8a2c-6c3cec64f7e0.png)
![screenshot from 2017-03-23 11-01-15](https://cloud.githubusercontent.com/assets/19604984/24237648/d7302012-0faf-11e7-8a7c-672a0009a8b5.png)

after ı ran code this is what exactly ı got .

**Comment by anfederico** [comment]
I'm not sure, there's no error message. When you start the program, and you visit the empty page, does an error message appear in console after you try to visit the empty page?

**Comment by diablordking** [comment]
Nope .There is no error message. I think bokeh server doesn't get data .

**Comment by hsk2017** [comment]
Hello, I get the same error. What was the solution to this?

Btw, this package is excellent. Congrats!
