### ISSUE TITLE
New to python

### ISSUE THREAD

**Issue by kirshanluhana** [Crypto-AI/Stocktalk#5]
hi
your app seems very useful for my research work, I made successfully setup , need some guideline to run program

Installation 
pip install stocktalk .... Done
Download Corpus
python -m nltk.downloader vader_lexicon .... Done

Twitter Streaming

Problem : In which file I should find and update API details ? 
and then how can I run application to collect data ? 

Can you please share some details ?

**Comment by anfederico** [comment]
Hey so the first file can be called streaming.py

```python
from stocktalk import streaming

# Credentials to access Twitter API 
API_KEY = 'XXXXXXXXXX'
API_SECRET = 'XXXXXXXXXX'
ACCESS_TOKEN = 'XXXXXXXXXX'
ACCESS_TOKEN_SECRET = 'XXXXXXXXXX'
credentials = [API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET]

# First element must be ticker/name, proceeding elements are extra queries
TSLA = ['TSLA', 'Tesla']
SNAP = ['SNAP', 'Snapchat']
AAPL = ['AAPL', 'Apple']
AMZN = ['AMZN', 'Amazon']

# Variables
tickers = [TSLA,SNAP,AAPL,AMZN]  # Used for identification purposes
queries =  TSLA+SNAP+AAPL+AMZN   # Filters tweets containing one or more query 
refresh = 30                     # Process and log data every 30 seconds

# Create a folder to collect logs and temporary files
path = "/Users/Anthony/Desktop/Data/"

streaming(credentials, tickers, queries, refresh, path, \
realtime=True, logTracker=True, logTweets=True, logSentiment=True, debug=True)
```

The second file can be called visualize.py
```python
from stocktalk import visualize

# Make sure these variables are consistent with streaming.py
tickers = ['TSLA','SNAP','AAPL','AMZN']
refresh = 30
path = "/Users/Anthony/Desktop/Data/"

visualize(tickers, refresh, path)
```

The second file needs the first file to be running, so run streaming.py
While it's running, go into your terminal and cd to the directory containing visualize.py
Once you're there, type: python -m bokeh serve --show visualize.py

**Comment by kirshanluhana** [comment]
Great, thanks for guide, it works perfect. 

Just one more question, I am getting tweets in different languages, can I restrict to English only ?

**Comment by anfederico** [comment]
You can restrict tweets to English only (should be somewhere in the Tweepy docs) however you can't grab past tweets.

**Comment by LimeCitron** [comment]
In my case, I changed the 'streaming.py' partial code from

from stocktalk import streaming

to

#-- coding: utf-8 --
from stocktalk import streaming
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

I was able to search for Unicode characters this way. 
I tested it in Korean and tweets were searched without any problems.
